import type { Metadata } from "next";
import { Geist, Geist_Mono, Catamaran } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import { ClerkProvider } from "@clerk/nextjs";

const catamaran = Catamaran({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${catamaran.className} text-dark-400 relative`}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
